<?php
class block_world_clock extends block_base{

    public function init(){
        $this->title = get_string('pluginname', 'block_world_clock');
    }
    public function applicable_formats() {
        return parent::applicable_formats(); // TODO: Change the autogenerated stub
    }
    public function get_content() {
        global $CFG, $DB, $OUTPUT,$PAGE;
        if($this->content !== NULL) {
            return $this->content;
        }
        //Dont show the block if the google maps apiv3 key is not setup

        $google_map_key_config = get_config('googlemapkey3');
        if(empty($google_map_key_config)){
            return $this->content;
        }
        echo "<script type='text/javascript' src='/moodle/blocks/world_clock/amd/build/moment.js'></script>'";
        echo "<script type='text/javascript' src='/moodle/blocks/world_clock/amd/build/moment-timezone-with-data.js'></script>'";
        echo "<script type='text/javascript'>
console.log(moment().tz(\"America/Los_Angeles\").format());
</script>";
        //$PAGE->requires->js_call_amd('block_world_clock/worldclock', 'initialise', []);
        //Show local time
        $actionurl = new moodle_url($PAGE->url, array('sesskey'=>sesskey()));
        $select = new single_select($actionurl, 'tz_selector', core_date::get_list_of_timezones(), null, array(''=>get_string('adddots')), 'add_block');
        //$select->set_label(get_string('addblock'), array('class'=>'accesshide'));
        $this->content->text = $OUTPUT->render($select);
        return $this->content;
    }

}